version: '3.8'

services:
  basket.api:
    container_name: lde.basket.api
    build:
      context: .
      dockerfile: Basket/Basket.Host/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5003
      - Authorization__Authority=http://www.alevelwebsite.com:5002
      - Redis__Host=www.alevelwebsite.com:6380
      - PathBase=http://www.alevelwebsite.com:5003
    depends_on:
      - redis
    ports:
      - 5003:5003
  catalog.api:
    container_name: lde.catalog.api
    build:
      context: .
      dockerfile: Catalog/Catalog.Host/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5000
       - ConnectionString=server=www.alevelwebsite.com;port=5433;database=catalog;uid=postgres;password=postgres;
       - Authorization__Authority=http://www.alevelwebsite.com:5002
       - PathBase=http://www.alevelwebsite.com:5000
    depends_on:
      - postgres
    ports:
      - 5000:5000  
  identityserver:
    container_name: lde.identityserver
    build:
      context: .
      dockerfile: IdentityServer/IdentityServer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - MvcUrl=http://www.alevelwebsite.com
      - ReactClientUrl=http://www.alevelwebsite.com:3000
      - CatalogApi=http://www.alevelwebsite.com:5000
      - BasketApi=http://www.alevelwebsite.com:5003
      - PaymentApi=http://www.alevelwebsite.com:5008
    ports:
      - 5002:5002  
  pgadmin4:
    image: dpage/pgadmin4
    container_name: lde.pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - 8001:80 
  postgres:
    image: postgres
    container_name: lde.postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
  redis:
    image: redis
    container_name: lde.redis
    ports:
      - 6380:6379
  payment.api:
    container_name: lde.payment.api
    build:
      context: .
      dockerfile: Payment.Proccessor/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5008
      - Authorization__Authority=http://www.alevelwebsite.com:5002      
      - PathBase=http://www.alevelwebsite.com:5008   
    ports:
      - 5008:5008 
  nginx-react:    
    container_name: lde.nginx.react    
    build:
       context: ./React/my-app/
       dockerfile: Dockerfile
    ports:
      - 3000:80   
  nginx-images:
    image: nginx:latest
    container_name: lde.nginx.images
    volumes:
      - ./Proxy/gateway/nginx/conf.d/nginx_image.conf:/etc/nginx/conf.d/default.conf
      - ./Proxy/assets:/var/www/assets
    ports:
      - 80:80 
networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1